# Request
string command      # "2r", "4b", "vw", "st_est", "sp_est" 등의 명령
---
# Response
float64 x           # mm 단위
float64 y           # mm 단위
float64 z           # mm 단위
float64 rz          # degree 단위 yaw
bool success
string view_result
